// <auto-generated />
using System;
using API_SITE_Mulher.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_SITE_Mulher.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_SITE_Mulher.Model.Domain.tb_categoria_de_posteres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name_categoria");

                    b.Property<string>("NomeTag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_tag");

                    b.HasKey("Id");

                    b.ToTable("tb_categoria_de_posteres");
                });

            modelBuilder.Entity("API_SITE_Mulher.Model.Domain.tb_poster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataDaPublicacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_de_publicacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("tbUsuariosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tbUsuariosId");

                    b.ToTable("tb_poster");
                });

            modelBuilder.Entity("API_SITE_Mulher.Model.Domain.tb_usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .HasColumnType("longtext")
                        .HasColumnName("apelido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_completo");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("roles");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senhar");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("tb_categoria_de_posterestb_poster", b =>
                {
                    b.Property<int>("tbCategoriaDePosteresId")
                        .HasColumnType("int");

                    b.Property<int>("tbPostersId")
                        .HasColumnType("int");

                    b.HasKey("tbCategoriaDePosteresId", "tbPostersId");

                    b.HasIndex("tbPostersId");

                    b.ToTable("tb_categoria_de_posterestb_poster");
                });

            modelBuilder.Entity("API_SITE_Mulher.Model.Domain.tb_poster", b =>
                {
                    b.HasOne("API_SITE_Mulher.Model.Domain.tb_usuario", "tbUsuarios")
                        .WithMany("PosteresDoUsuario")
                        .HasForeignKey("tbUsuariosId");

                    b.Navigation("tbUsuarios");
                });

            modelBuilder.Entity("tb_categoria_de_posterestb_poster", b =>
                {
                    b.HasOne("API_SITE_Mulher.Model.Domain.tb_categoria_de_posteres", null)
                        .WithMany()
                        .HasForeignKey("tbCategoriaDePosteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_SITE_Mulher.Model.Domain.tb_poster", null)
                        .WithMany()
                        .HasForeignKey("tbPostersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_SITE_Mulher.Model.Domain.tb_usuario", b =>
                {
                    b.Navigation("PosteresDoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
